### ISSUE TITLE
Is this tool ready?

### ISSUE THREAD

**Issue by linwaytin** [emacs-languagetool/flycheck-languagetool#3]
Hi, I'm looking for a grammar checker for LaTeX files.
It seems this package is not on Melpa yet. 
Can I use it now?
I'm also curious if this tool can work on LaTeX files.
Thanks for making this package.

**Comment by jcs090218** [comment]
Hi, @linwaytin 

Yes, I just finished the work for this package today. Feel free to use it and give some feedback for this package. The reason why this isn't on MELPA yet is because I have another package under review and I will soon publish to MELPA once another package is done reviewing by MELPA's maintainer.

Thanks for reaching out!

**Comment by jcs090218** [comment]
This is on MELPA now. Closing this issue. 👍

**Comment by linwaytin** [comment]
Thanks for your work on LanguageTool!
